name = "my-closet"
compatibility_date = "2024-09-23"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "closet-db"
database_id = "af7009ab-9517-432d-a076-ca04d769ad5e"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "closet-photos"
